### ISSUE TITLE
[Feature Request] - translations

### ISSUE THREAD

**Issue by evroom** [Ax-LED/MMM-Dreambox#1]
Feature Request:

Translation files (eq en.json, de.json, nl.json) for module headers.

Examples:
Modell: dm7020hd - derzeit läuft: XXX

Model: dm7020hd - now playing: XXX
Model: dm7020hd - current channel: XXX

Model: dm7020hd - momenteel kanaal: XXX

**Comment by Ax-LED** [comment]
Done, do a git pull of the module.

**Comment by evroom** [comment]
Works fine.
Thanks.
