### ISSUE TITLE
[Feature Request] - X services before and after current service.

### ISSUE THREAD

**Issue by evroom** [Ax-LED/MMM-Dreambox#3]
Feature Request:

An option in config.js to show X services before and after current active service.
Like:

showServices: 5,

Meaning: show 5 services before the current active service and 5 services after the current active service.

I have 50+ services in my Favourites (TV) bouquet and this takes up a large part of my mirror.

**Comment by Ax-LED** [comment]
This request isnt that easy, as i use the order of the "untrimed" xml structure to add some informations (like epg) and the structure is also used to navigate inside the module. So i am not sure if i implement this request. A possible workaround would be, to make a own **bouquet** for the receiver/MM.
AxLED

**Comment by evroom** [comment]
Okay.
Let's say I have the bouquet "MagicMirror (TV)", could there be an option to use this one, instead of the default "Favourites (TV)" ?
I assume "Favourites (TV)" is the default.

**Comment by evroom** [comment]
Basically this would be "[Feature Request] - selection of bouquet".

**Comment by Ax-LED** [comment]
done, see [feature request #2](https://github.com/Ax-LED/MMM-Dreambox/issues/2)
