### ISSUE TITLE
[Feature Request] - change text services without EPG info

### ISSUE THREAD

**Issue by evroom** [Ax-LED/MMM-Dreambox#4]
Feature Request:

Services without EPG info show as:

ServiceName - (Invalid date None)

Nicer would be:

ServiceName - ()

or:

ServiceName - (No EPG)

or:

ServiceName - (No EPG available)

I personally would prefer the first, as I have around 10 services that do not have EPG info available.
Or one could add it to a translation file.

**Comment by Ax-LED** [comment]
@evroom 
i will implement this feature request, what would be the nl translation for "no epg"?
AxLED

**Comment by evroom** [comment]
Thanks.

NL Translation would be:

“Geen EPG”

**Comment by Ax-LED** [comment]
@evroom 
Found another textstring which should be translated. If a recording is active i show "recording: (Big Bang Theorie (RTL HD)", what would be the nl translation for "recording"?
AxLED

**Comment by evroom** [comment]
“opname” or perhaps better “video-opname”.

**Comment by Ax-LED** [comment]
Done, do a git pull of the module.

**Comment by evroom** [comment]
Works fine.
Thanks.
