### ISSUE TITLE
[Feature Request] - get sRef and bRef information from getservices.

### ISSUE THREAD

**Issue by evroom** [Ax-LED/MMM-Dreambox#6]
Make the config.js easier by using getservices.

Parameters apiepgnow and apiServicelistplayable use complicated bRef and sRef strings.
First of all they seem to be identical and second of all there is a way to get them by using:

http://192.168.178.47/web/getservices

This gives the sRef/bRef for all bouquets.
Example for one bouquet:
1:7:1:0:0:0:0:0:0:0:FROM BOUQUET "userbouquet.favourites.tv" ORDER BY bouquet

You can convert them by using encodeURI(uri) in JavaScript:

https://www.w3schools.com/jsref/jsref_encodeuri.asp

This gives:

1%3A7%3A1%3A0%3A0%3A0%3A0%3A0%3A0%3A0%3AFROM%20BOUQUET%20%22userbouquet.favourites.tv%22%20ORDER%20BY%20bouquet

Just a proposal in order to make it easier for the user to not have to set this parameter him/her-self.

Note that the apibouquet parameter will determine which bouquet will be chosen.

**Comment by Ax-LED** [comment]
Hi,
i already thouhgt of that, this would reduce complexity on config.js site to get a receiver running.
I am not sure how to implement that, as i pass the bRef / sRef as part of a config parameter link from module.js to the node_helper (once).
Getting the value of [number] bRef / sRef (if you have more than one bouquet) can first be done inside node_helper.js.
If i have an idea and some time i try to implement your "our" request.

AxLED

**Comment by evroom** [comment]
I never made a module, so I have no idea about the interaction between module js and the node helper.
Perhaps I should try it one time :-)
Automating it makes it easier to use the apibouquet parameter.
But perhaps for most users it is a onetime exercise..

**Comment by Ax-LED** [comment]
@evroom 
Check out the dev branch of my module, i made it to reduce complexity for the two `sRef` and `bRef` values. Now you only have to put `apibouquet: 0,` (or different number) into config.js and rest is done by the module.
For later readers: If dev branch isnt available anymore it was integrated into the master branch.
I also added some features, see screenshots and readme of dev branch.

AxLED
