### ISSUE TITLE
TypeError: Cannot read property 'apibouquet' of undefined

### ISSUE THREAD

**Issue by evroom** [Ax-LED/MMM-Dreambox#9]
Installed the latest dev branch.
The logs show:
`TypeError: Cannot read property 'apibouquet' of undefined`

My config.js
  ```
{
      module: 'MMM-Dreambox',
      position: 'bottom_left',
      disabled: false,
      header: 'Vu+ Duo²',
      config: {
        //apiBase: 'http://192.168.178.46:80',
        apiBase: 'http://192.168.178.28:80',
        omxargs: ' --genlog --win 320,180,1600,900  -o both ',
        refreshInterval: 1000 * 30, //refresh every 30 seconds
        apibouquet: 0,
        apiRecordingsID: 1,
        listmax: 10
      }
  },
```

pm2 logs:

```
0|mm  | Starting node helper for: MMM-Dreambox
0|mm  | Whoops! There was an uncaught exception...
0|mm  | TypeError: Cannot read property 'apibouquet' of undefined
0|mm  |     at Request._callback (/home/pi/MagicMirror/modules/MMM-Dreambox/node_helper.js:353:81)
0|mm  |     at Request.self.callback (/home/pi/MagicMirror/node_modules/request/request.js:185:22)
0|mm  |     at emitTwo (events.js:126:13)
0|mm  |     at Request.emit (events.js:214:7)
0|mm  |     at Request.<anonymous> (/home/pi/MagicMirror/node_modules/request/request.js:1157:10)
0|mm  |     at emitOne (events.js:116:13)
0|mm  |     at Request.emit (events.js:211:7)
0|mm  |     at IncomingMessage.<anonymous> (/home/pi/MagicMirror/node_modules/request/request.js:1079:12)
0|mm  |     at Object.onceWrapper (events.js:313:30)
0|mm  |     at emitNone (events.js:111:20)
```

**Comment by Ax-LED** [comment]
@evroom 
Thanks for testing, i found a little bug and corrected it, please do a `git pull` of dev branch, no it should work.
I am looking forward to hear your feedback.

AxLED

**Comment by evroom** [comment]
It works now.

Now the next thing.
How to get into Recordings mode ?

I tried adding

       apiLocations: '/web/getlocations',
        apiMovielist: '/web/movielist?dirname=/media/hdd/movie'

But it still shows the channel list.

**Comment by evroom** [comment]
Okay. Did not pay attention to this change:
yourmmip:8080/remote?action=NOTIFICATION&notification=DB-RECORDINGS selects recordings mode

**Comment by evroom** [comment]
It does not show the recordings.

http://192.168.178.46/web/getlocations

```
<e2locations>
<e2location>/hdd/movie/</e2location>
<e2location>/media/net/DM7020HD/</e2location>
</e2locations>
```

http://192.168.178.46/web/movielist?dirname=/media/hdd/movie

`<e2movielist></e2movielist>`

There are a ton of recordings under /media/hdd/movie.
Do not know why the e2movielist is empty.

**Comment by evroom** [comment]
Good.
Nothing is needed, just the DB-RECORDINGS.
Works like a charm.
Well done !!

**Comment by Ax-LED** [comment]
@evroom 
So now every works like it should? I am looking forward to your answer, so i can close this issue.
AxLED

**Comment by evroom** [comment]
Yes, all is fine.
Issue can be closed.
